### ISSUE TITLE
[Request Feature] Generalize Google Colab Code for Video Colorization

### ISSUE THREAD

**Issue by DanialPahlavan** [yyang181/colormnet#13]
Hi,

I noticed that your model can colorize videos, but the Google Colab code provided is limited to a single sample video. Could you please modify the Colab code to allow it to be used with any video? I would like to test the model on various videos and scenarios.

Thank you very much!

**Comment by yyang181** [comment]
Hi @DanialPahlavan,

I’ve updated the Colab demo to support any video and exemplar as input. Let me know if you have any questions!

**Comment by DanialPahlavan** [comment]
@yyang181 thanks a lot.
