### ISSUE TITLE
Evaluation dataset and score for NTIRE 2023 - Video Colorization Challenge

### ISSUE THREAD

**Issue by agusgun** [yyang181/colormnet#3]
Hi, can I know how you get the PSNR and SSIM score of NTIRE 2023 - Video Colorization Challenge dataset since the validation images GT are not released in their repository. If possible, can you share the evaluation dataset?

Thank you so much.

**Comment by yyang181** [comment]
Hi @agusgun,

The organizers of the NTIRE 2023 - Video Colorization Challenge provide **validation** images with ground truth (GT) but do not provide ground truth for the **test** images. For further details, please refer to the competition page at [this link](https://tianchi.aliyun.com/competition/entrance/532054/information).

I've also included a screenshot for your reference.

<img width="1007" alt="image" src="https://github.com/yyang181/colormnet/assets/38424900/5488f5fc-a723-4198-8bad-56f6c5f426d3">
